import arcade.color

# Core settings
WIDTH = HEIGHT = 800
ANT_COUNT = 10
FOOD_STOCK_COUNT = 3

# Sizes and distances
ANT_SIZE = 10
NEST_RADIUS = 45
GRID_CELL_SIZE = 50
PHEROMONE_MERGE_DISTANCE = 10

# Simulation parameters
PHEROMONE_INITIAL_STRENGTH = 100
EVO_HOME_RATE = 0.05
EVO_FOOD_RATE = 0.02
FOOD_INITIAL_STOCK = 25
FOOD_BITE_SIZE = 1

# Colors
NEST_COLOR = arcade.color.BLUE
FOOD_COLOR = arcade.color.ORANGE
ANT_COLOR = arcade.color.WHITE
