import arcade.color

# Window settings
WIDTH = HEIGHT = 800

# Game entities
ANT_COUNT = 100
ANT_SIZE = 3  # Reduced from 10
FOOD_STOCK_COUNT = 10
FOOD_INITIAL_STOCK = 25
FOOD_BITE_SIZE = 1
NEST_RADIUS = 45

# Pheromone settings
PHEROMONE_INITIAL_STRENGTH = 100
PHEROMONE_MERGE_DISTANCE = 10
GRID_CELL_SIZE = 50
EVO_HOME_RATE = 0.05
EVO_FOOD_RATE = 0.02

# Colors
NEST_COLOR = arcade.color.DARK_BLUE
FOOD_COLOR = arcade.color.GOLD
ANT_COLOR = arcade.color.LIGHT_GRAY
PHEROMONE_FOOD_COLOR = arcade.color.LIGHT_GREEN
PHEROMONE_HOME_COLOR = arcade.color.LIGHT_BLUE
